import 'package:izipay_sdk/izipay_sdk_platform_interface.dart';

/// Main entry point for the Izipay SDK Flutter plugin.
///
/// Exposes [payWithCard], [payWithYape] and a stream-based [resultStream]
/// that emits a single [IziPayResult] after each payment attempt.
///
/// Example:
/// ```dart
/// final izipay = FlutterIzipay();
///
/// final sub = izipay.resultStream.listen((result) {
///   if (result.success) {
///     print('Token: ${result.card.cardToken}');
///   }
/// });
///
/// await izipay.payWithYape(
///   config: (environment: 'SBOX', merchantCode: '...', publicKey: '...', transactionId: '...'),
///   transactionId: 'TXN-001',
///   amount: '50.00',
///   user: (...),
///   address: (...),
///   theme: (logoUrl: 'https://...'),
/// );
///
/// sub.cancel();
/// ```
class FlutterIzipay {
  /// Response code returned by Izipay when a payment succeeds.
  static const kIzipaySuccess = '00';

  /// Broadcasts a single [IziPayResult] each time the Izipay SDK
  /// returns a result (success or failure).
  ///
  /// Subscribe before calling [payWithCard] or [payWithYape], and cancel
  /// the subscription when you are done.
  Stream<IziPayResult> get resultStream {
    return FlutterIzipayPlatform.instance.resultStream().map((e) {
      final code = (e['code'] as String?) ?? '';
      return (
        success: code == kIzipaySuccess,
        code: code,
        card: IziPayCardExtension.fromJson(e),
      );
    });
  }

  /// Opens the Izipay form to tokenize a card without charging it.
  ///
  /// > **Warning:** This method is not ready for production.
  /// > It is kept for forward compatibility and will throw on iOS.
  @Deprecated(
      'Not ready for production. Use payWithCard or payWithYape instead.')
  Future<void> openFormToSaveCard({
    required IziPayConfig config,
    required String transactionId,
    required IziPayUser user,
    required IziPayAddress address,
    required IziPayTheme theme,
    String webhookUrl = '_blank',
  }) {
    return FlutterIzipayPlatform.instance.openFormToSaveCard({
      ...config.toJson(),
      'transactionId': transactionId,
      'orderNumber': _adjust13Length(transactionId),
      'webhookUrl': webhookUrl,
      ...user.toJson(),
      ...address.toJson(),
      ...theme.toJson(),
    });
  }

  /// Launches the Izipay card payment form.
  ///
  /// - [config] — SDK configuration (environment, merchantCode, publicKey, transactionId).
  ///   The `publicKey` must be a session JWT generated by your backend.
  /// - [transactionId] — unique identifier for this transaction.
  /// - [amount] — total amount in PEN, formatted as a decimal string (e.g. `"99.90"`).
  /// - [orderNumber] — optional 13-character order number. Derived from [transactionId] if omitted.
  /// - [webhookUrl] — optional IPN endpoint. Defaults to `'_blank'` (no IPN).
  Future<void> payWithCard({
    required IziPayConfig config,
    required String transactionId,
    required String amount,
    required IziPayUser user,
    required IziPayAddress address,
    required IziPayTheme theme,
    String webhookUrl = '_blank',
    String? orderNumber,
  }) {
    return FlutterIzipayPlatform.instance.payWithCard({
      ...config.toJson(),
      'transactionId': transactionId,
      'orderNumber': orderNumber ?? _adjust13Length(transactionId),
      'webhookUrl': webhookUrl,
      'amount': amount,
      ...user.toJson(),
      ...address.toJson(),
      ...theme.toJson(),
    });
  }

  /// Launches the Izipay Yape payment form.
  ///
  /// Same parameters as [payWithCard]. The SDK will show only the Yape form.
  Future<void> payWithYape({
    required IziPayConfig config,
    required String transactionId,
    required String amount,
    required IziPayUser user,
    required IziPayAddress address,
    required IziPayTheme theme,
    String webhookUrl = '_blank',
    String? orderNumber,
  }) {
    return FlutterIzipayPlatform.instance.payWithYape({
      ...config.toJson(),
      'transactionId': transactionId,
      'orderNumber': orderNumber ?? _adjust13Length(transactionId),
      'webhookUrl': webhookUrl,
      'amount': amount,
      ...user.toJson(),
      ...address.toJson(),
      ...theme.toJson(),
    });
  }

  /// Ensures [value] is exactly 13 characters, padding with leading zeros
  /// or trimming from the left if longer.
  String _adjust13Length(String value) {
    if (value.length > 13) return value.substring(value.length - 13);
    return value.padLeft(13, '0');
  }
}

// ── Result types ─────────────────────────────────────────────────────────────

/// Result emitted by [FlutterIzipay.resultStream] after each payment attempt.
typedef IziPayResult = ({
  /// Whether the payment succeeded (code == `'00'`).
  bool success,

  /// Raw response code from the Izipay SDK.
  /// `'00'` means success; `'021'` means the user closed the form.
  String code,

  /// Card data returned on success. Fields are empty strings on failure.
  IziPayCard card,
});

/// Tokenised card data returned by the Izipay SDK on a successful payment.
typedef IziPayCard = ({
  /// Izipay card token for future charges.
  String cardToken,

  /// Masked card PAN (e.g. `'411111XXXXXX1111'`).
  String cardPan,

  /// Card brand (e.g. `'visa'`, `'mastercard'`).
  String cardBrand,
});

// ── Input types ───────────────────────────────────────────────────────────────

/// SDK-level configuration required for every payment call.
typedef IziPayConfig = ({
  /// Deployment environment. Use `'SBOX'` for sandbox or `'PROD'` for production.
  String environment,

  /// Your Izipay merchant code.
  String merchantCode,

  /// Session JWT generated by your backend via `generateTokenPayV2PW2`.
  /// This value is labelled `publicKey` in the SDK but contains a short-lived token.
  String publicKey,

  /// Unique transaction identifier (UUID or similar).
  String transactionId,
});

/// Buyer information required by the Izipay SDK.
typedef IziPayUser = ({
  String userId,
  String firstName,
  String lastName,
  String email,
  String phoneNumber,

  /// Document type (e.g. `'DNI'`, `'RUC'`).
  String documentType,
  String documentNumber,
});

/// Billing address required by the Izipay SDK.
typedef IziPayAddress = ({
  String street,
  String city,
  String state,

  /// ISO 3166-1 alpha-2 country code (e.g. `'PE'`).
  String country,
  String postalCode,
});

/// Visual customisation for the Izipay payment form.
typedef IziPayTheme = ({
  /// Publicly accessible URL of your logo image.
  String logoUrl,
});

// ── Extensions ────────────────────────────────────────────────────────────────

extension IziPayAddressExtension on IziPayAddress {
  Map<String, String> toJson() => {
        'street': street,
        'city': city,
        'state': state,
        'country': country,
        'postalCode': postalCode,
      };
}

extension IziPayCardExtension on IziPayCard {
  static IziPayCard fromJson(Map<String, dynamic> json) => (
        cardToken: (json['cardToken'] as String?) ?? '',
        cardPan: (json['cardPan'] as String?) ?? '',
        cardBrand: (json['cardBrand'] as String?) ?? '',
      );

  static IziPayCard withToken(String cardToken) => (
        cardToken: cardToken,
        cardPan: '',
        cardBrand: '',
      );
}

extension IziPayThemeExtension on IziPayTheme {
  Map<String, String> toJson() => {'logoUrl': logoUrl};
}

extension IziPayUserExtension on IziPayUser {
  Map<String, String> toJson() => {
        'userId': userId,
        'firstName': firstName,
        'lastName': lastName,
        'email': email,
        'phoneNumber': phoneNumber,
        'documentType': documentType,
        'documentNumber': documentNumber,
      };
}

extension IziPayConfigExtension on IziPayConfig {
  Map<String, String> toJson() => {
        'environment': environment,
        'merchantCode': merchantCode,
        'publicKey': publicKey,
      };
}
